Numpy is used to do bulk operations and is allowed to exploit parallelism if it is possible to parallelize(vectorized code).

### Numpy Basics

#### Array

An array is essentially a list but is homogeneous. Mimics n-dimensional structure.

In [1]:
# importing
import numpy as np

In [2]:
# creating 1-d array
array_1d = np.array([2, 4, 5, 6, 7, 8, 9])
print(array_1d)
print(type(array_1d))

[2 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [3]:
# creating 2-d array
array_2d = np.array([[2,3,4], [5,8,7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


Numpy dimensions are called axis.

axis = 0 ------> refers to rows
axis = 1 ------> refers to columns


            <-------------axis = 1----------->
                col1    col2     col3
         row0
         row1
         row2

In [4]:
# 3-d array
list_1 = [1,2,3]
list_2 = [4,5,6]
list_3 = [7,8,9]

array_1 = np.array([list_1, list_2, list_3])

print(array_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Array Operations

In [5]:
# normally in python, this is how we multiply elements in 2 lists

list_1 = [1,2,3]
list_2 = [4,5,6]

product_list = list(map(lambda x,y : x*y, list_1, list_2))
print(product_list)

[4, 10, 18]


In [6]:
# Numpy array we to do the above operation

array_1 = np.array(list_1)
array_2 = np.array(list_2)

array_3 = array_1 * array_2
print(array_3)

[ 4 10 18]


Note:

Operators operate on every element of array.

Incase of binary operations on array, it is important that the size of array or dimensions of array should be same.


#### Creating  Numpy Arrays

1. Using np.array()
2. Convert list of tuples to array using np.array()
3. np.ones() ----> Create an array of 1's
4. np.zeros()----> Create an array of 0's
5. np.random.random()---> Create an array of random numbers between 0 and 1
6. np.arange()---> Create an array with increments of a fixed step size
7. np.linspace()--> Create an array of fixed length

In [7]:
array_from_list = np.array([1, 2, 3, 4])
array_from_tuple = np.array((9, 4, 5, 6))

print(array_from_list)
print(array_from_tuple)

[1 2 3 4]
[9 4 5 6]


In [8]:
np.ones((2,3)) # creating 2x3 arrayof ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.ones((2,3), dtype=np.int) # setting datatype as int

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros(4, dtype=np.int)

array([0, 0, 0, 0])

In [12]:
np.random.random([3,4]) # np.random.random([row,column])

array([[0.09614672, 0.14488646, 0.22297876, 0.9860321 ],
       [0.12487562, 0.51157013, 0.44167295, 0.28594282],
       [0.82060935, 0.95462772, 0.21716824, 0.98576814]])

In [13]:
np.arange(10,100,5) # range 10 to 100 with step size of 5

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [14]:
np.linspace(15, 18, 25) # 25 values from 15 to 18

array([15.   , 15.125, 15.25 , 15.375, 15.5  , 15.625, 15.75 , 15.875,
       16.   , 16.125, 16.25 , 16.375, 16.5  , 16.625, 16.75 , 16.875,
       17.   , 17.125, 17.25 , 17.375, 17.5  , 17.625, 17.75 , 17.875,
       18.   ])

#### Some more numpy array creations

1. np.full() ----> Create a constant array of any number 'n'
2. np.tile() ----> Create a new array by repeating an existing array for a particular no. of times
3. np.eye()  ----> Create an identity matrix of any dimension
4. np.random.radint()---> Create a random array of int within particular range

In [15]:
np.full([3,4], 1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
np.eye(4, dtype=np.int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [17]:
a = np.array([0, 1, 2])
print(a)
b = np.tile(a, 4)
print(b)

[0 1 2]
[0 1 2 0 1 2 0 1 2 0 1 2]


In [18]:
np.random.randint( 3, size=(5,5)) # using 3 int values create an array of size given

array([[0, 1, 0, 0, 2],
       [0, 2, 0, 0, 2],
       [2, 1, 0, 1, 1],
       [1, 1, 1, 0, 2],
       [2, 1, 0, 2, 1]])

#### Basics 2

1. shape ---> shape of an array(nxm)
2. dtype ---> datatype (int, float)
3. ndim ---> No. of dimensions (or axis)
4. itemsize ---> Memory used by each array element in bytes

In [22]:
rand_array = np.random.random((1000,3000))
print(rand_array)

[[0.82796641 0.40910037 0.36463515 ... 0.03803542 0.69226713 0.75592071]
 [0.99876667 0.86174818 0.9699341  ... 0.35681389 0.24675939 0.93332407]
 [0.97797762 0.99153382 0.62444285 ... 0.21325909 0.85482996 0.51825257]
 ...
 [0.22160282 0.94697765 0.29984082 ... 0.74655699 0.66627727 0.33623481]
 [0.86135904 0.09701761 0.7937403  ... 0.20234117 0.20138608 0.75888263]
 [0.22853118 0.75428846 0.39770191 ... 0.8292689  0.03285996 0.44748701]]


In [25]:
print(rand_array[0,]) # printing first row

[0.82796641 0.40910037 0.36463515 ... 0.03803542 0.69226713 0.75592071]


In [34]:
# creating a 3d array

#reshape simply reshapes a 1D array

array_1d = np.arange(24) # printing row from 0 to 23

print(array_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [52]:
array_3d = array_1d.reshape(2,3,4) # 2 sub-arrays, 3 rows in each sub-arrays and 4 columns
print(array_3d) # here R1 = 2, R2 = 3 and C = 4 (2 slices of 3 X 4)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [53]:
print(array_3d[0][1][2]) # ans should be 6

6


#### Subset, Slice, Index and Iterate through Arrays

In [55]:
array_1d = np.arange(10) # print row 0 to 9
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
# print third element

print(array_1d[2])

2


In [65]:
# array [2,5,6] will throw an error. We must provide the indices as a list

print(array_1d[[2,4,6]]) # retrieving elements at index 2,4 and 6 as a list

[2 4 6]


In [67]:
# slice first 3 elements

print(array_1d[:3])

[0 1 2]


In [70]:
# slice 3rd to 7th element

print(array_1d[2:7])

[2 3 4 5 6]


In [71]:
# subset starting 0 at increment of 2

print(array_1d[0::2])

[0 2 4 6 8]


In [74]:
for i in array_1d:
    print(i**2)

0
1
4
9
16
25
36
49
64
81


#### Multi-dimensional Arrays

Multi-dimensional arrays are indexed using as many indices as the number of dimensions or axes.

For instance, to index a 2-D array you need 2 indices -> array[x,y]

Each index has an index starting at 0. The following figure shows the axes and their indices for a 2-D array.


In [78]:
# Creating a 2-D array

array_2d = np.array([[2,5,7,5],
                    [4,6,8,10],
                    [10,12,15,19]])

print(array_2d)

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [79]:
# Third row second column
# printing 12

print(array_2d[2,1])

12


In [86]:
# slicing 2nd row and all columns

print(array_2d[1,:])

[ 4  6  8 10]


In [84]:
print(type(array_2d[1,:]))

<class 'numpy.ndarray'>


In [92]:
# slicing all rows and first 3 columns

print(array_2d[:,:3])

[[ 2  5  7]
 [ 4  6  8]
 [10 12 15]]


Iterating on 2-D array is done w.r.t the first axis (which is row), the second axis (which is column)

In [96]:
for row in array_2d:
    print(row[0])

2
4
10


In [97]:
#Iterating over 3-d array  done w.r.t the first axis 

array_3d = np.arange(24).reshape(2,3,4) # 2 * 3 * 4 = 24
print(array_3d)



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [101]:
# print 2 blocks

for row in array_3d:
    print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


#### Basic Operation on Arrays

reshape ---> change shape of an array

(2 x 3 x 4) can reshape to (1 x 3 x 8)

To re-arrange elements of an array into a multidimensional box

In [109]:
import numpy as np

some_array = np.arange(0,12).reshape(3,4)
print(some_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [110]:
# can reshape it further 

some_array.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [111]:
# if we specify -1 as a dimensions, then the dimensions are automatically calculated
# -1 means whatever dimension is needed 

some_array.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [114]:
print(some_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [115]:
# Finding Transpose of array

print(some_array.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


#### horizontal stacking :
rows must be same

#### vertical stacking
columns must be same

In [116]:
array_1 = np.arange(12).reshape(3,4)
array_2 = np.arange(20).reshape(5,4)

In [118]:
print(array_1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [119]:
print(array_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [123]:
# vertical stacking

# Note that np.vstack(a,b) will throw an error
# we need to pass arrays as a list

np.vstack((array_1, array_2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [125]:
np.vstack([array_1, array_2])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [127]:
# creating arrays for hstack


array_1 = np.arange(15).reshape(5,3)
array_2 = np.arange(20).reshape(5,4)

In [129]:
print(array_1)
print("\n")
print(array_2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [131]:
np.hstack((array_1, array_2))

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11],
       [ 9, 10, 11, 12, 13, 14, 15],
       [12, 13, 14, 16, 17, 18, 19]])

#### Vectorized Operations on Arrays

In [133]:
a = np.arange(1,20)

print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [139]:
# sin, cos, exp, log
# performs on every elements of arrays
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721]


In [140]:
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396
  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334  0.66031671
  0.98870462]


In [141]:
print(np.exp(a))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08]


In [142]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176
 2.94443898]


In [143]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [147]:
# the non-numpy way - not recommended
a_list = [x/(x+1) for x in a]
print(a_list)

[0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.9285714285714286, 0.9333333333333333, 0.9375, 0.9411764705882353, 0.9444444444444444, 0.9473684210526315, 0.95]


In [148]:
# numpy way - vectorize the function and then apply - recommended

f = np.vectorize(lambda x : x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

#### Linear Algebra


Numpy provides np.linalg to apply common linear algebra operations such as:

1. np.linalg.inv ---> inverse of a matrix
2. np.linalg.det ---> determinant of a matrix
3. np.linalg.eig ---> eigen values and eigen vectors of matrix

all of the above will only work for 2d matrices and wont work for higher dimensional matrices.

In [150]:
# creating arrays

a = np.arange(1,10).reshape(3,3)
b = np.arange(1,13).reshape(3,4)

In [151]:
print(a)
print("\n")
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [152]:
# inverse

np.linalg.inv(a)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [153]:
# Matrix multiplication
# Not element wise - but multiply matrix
# 1st row of matrix-1 with 1st column of matrix-2 and so on
# Also called dot product of 2 matrices

np.dot(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])