Numpy is used to do bulk operations and is allowed to exploit parallelism if it is possible to parallelize(vectorized code).

### Numpy Basics

#### Array

An array is essentially a list but is homogeneous. Mimics n-dimensional structure.

In [2]:
# importing
import numpy as np

In [7]:
# creating 1-d array
array_1d = np.array([2, 4, 5, 6, 7, 8, 9])
print(array_1d)
print(type(array_1d))

[2 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [9]:
# creating 2-d array
array_2d = np.array([[2,3,4], [5,8,7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


Numpy dimensions are called axis.

axis = 0 ------> refers to rows
axis = 1 ------> refers to columns


            <-------------axis = 1----------->
                col1    col2     col3
         row0
         row1
         row2

In [10]:
# 3-d array
list_1 = [1,2,3]
list_2 = [4,5,6]
list_3 = [7,8,9]

array_1 = np.array([list_1, list_2, list_3])

print(array_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Array Operations